<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dispatchers\**" />
    <Compile Remove="Queries\**" />
    <EmbeddedResource Remove="Dispatchers\**" />
    <EmbeddedResource Remove="Queries\**" />
    <None Remove="Dispatchers\**" />
    <None Remove="Queries\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rewardly.Domain\Rewardly.Domain.csproj" />
  </ItemGroup>

</Project>
